### ISSUE TITLE
Enhancement proposals

### ISSUE THREAD

**Issue by endlfall** [alserh3/pld_user_generator#1]
### This is not a complete guide on how to make this code 100% perfect, just a few tips you can use in the future!

Hey @alserh3. Great job, your script is very good. I want to provide feedback so you can improve your code even if it's not necessary.

----

## Naming

First of all, I would like to suggest that you do not shorten variable names. Even if you understand it,there are many different people who can easily get lost in variables (or functions) with bad names. I would suggest the following variable names:

1. `secList` -> `securitiesArray` (btw JS has no List, js has Arrays)
2. `curList` -> `currenciesArray`

Same for function names:
1. `createHold` -> `createHolding`
2. `createSingleTr` -> `createSingleTransaction`

It makes no sense to abbreviate all these names.

---

## Functions

You can easily improve the readability of your function by simply removing uselles lines of code.
Here is an example of what your `createHold` function might look like.

```js
function createHolding(security) {
  // scroll down to the last section to see how you can use .random() function
  const currency = currunciesArray.random();
  
  return {
    "institution_price": 10000 * Math.random(),
    "institution_price_as_of": "2023-08-01",
    "cost_basis": 10,
    "quantity": 100 * Math.random(),
    "currency": currency,
    "security": {
      "ticker_symbol": security,
      "currency": currency
    }
  }
}
```

## More functions

Try to put each piece of code that does the same thing in a separate function (this doesn't mean you should put each line of code in a separate function, but if you see multiple lines of code doing something, put them in a function)

Examples of code that you can move to the separate functions:

```js
console.log(`
For this instance: 
==============================
==========HOLDINGS============
==============================
`)
baseAcc.override_accounts[0].holdings.forEach(holding => console.log(`${holding.security.ticker_symbol} holding ${holding.quantity}`))

```

This function can even be split into two different functions and one will call the other internally.

```js
console.log(`
==============================
==========TRANSACTIONS========
==============================
`)
console.log(`Total Transactions: ${baseAcc.override_accounts[0].investment_transactions.length}
Total FEES: ${baseAcc.override_accounts[0].investment_transactions.reduce((totFee, fee) => totFee + fee.fees, 0)}
==============================
`)

secList.forEach(
  item => {
    let sumTransactions = baseAcc.override_accounts[0].investment_transactions.filter(i => i.security.ticker_symbol == item).reduce((total, current) => total + current.quantity, 0)
    console.log(`${item} TOTAL in TRANSACTIONS : ${sumTransactions} |||| EXPECTED COMPENSATORY TRANSACTION : ${(baseAcc.override_accounts[0].holdings.find(it => JSON.stringify(Object.values(it)).includes(item)).quantity) - sumTransactions}`)
  }
)
```

And in the result you will end up with this easialy understandable code

```js
let baseAccount = createBaseAccount();
printHoldings(baseAccount)
printTransactions(baseAccount)
```

## Small hack for getting random value

You can paste this code at the begging of this file

```js
Array.prototype.random = function () {
  return this[Math.floor((Math.random() * this.length))];
}
```

This will give you possibility to get random values like this

```js
[1, 2, 3, 4].random()
```

or even this

```js
securitiesArray.random()
```

**Comment by endlfall** [comment]
Also take a look at [linter](https://eslint.org/)

**Comment by alserh3** [comment]
Thank you, @endlfall ! This is super insightful. 

- I merged some changes according your advice 
- Added a logic (simplified) to recognize if the asset is identified via ISIN or TICKER (different keys used, impacts output) 
- my VSCode has linter extension

For the future I might wrap this code into HTML so it could be run with some visual integrity.
If you spot more weak points, please never hesitate to lmk!
Thanks again!

**Comment by endlfall** [comment]
@alserh3 looks much better, well done!
